# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Administrator/Desktop/Nexys4-DDR-DDR-SAMPLE-master/DDR_/src/constraints/Nexys4DDR_Master.xdc

# IP: C:/Users/Administrator/Desktop/Nexys4-DDR-DDR-SAMPLE-master/DDR_/src/ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
